"""user tokens

Revision ID: 52815a6f0b8d
Revises: 77e9b8d1729a
Create Date: 2018-03-29 10:18:00.157146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52815a6f0b8d'
down_revision = '77e9b8d1729a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
